### ISSUE TITLE
Remover arquivo .DS_Store da raiz do projeto

### ISSUE THREAD

**Issue by lhsazevedo** [comuREDE/core#14]
### Objetivo
Precisamos remover o arquivo `.DS_Store` localizado na raiz do projeto e garantir que ele não seja incluído em commits futuros. Esse arquivo é gerado automaticamente pelo macOS e não tem relevância para o projeto.

### Contexto
- **O que é o `.DS_Store`?**: É um arquivo oculto criado pelo macOS para armazenar preferências de visualização da pasta. Ele não é necessário para o funcionamento do projeto.
- **Problema**: A presença do `.DS_Store` no repositório adiciona um arquivo inútil, poluindo o histórico de commits e criando potenciais conflitos de merge. 
- **Relevância no Projeto**: Manter o repositório limpo e organizado facilita a colaboração e evita problemas desnecessários.

### Tarefas
- Remover o arquivo `.DS_Store` presente na raiz do projeto.
- Adicionar o arquivo `.DS_Store` ao `.gitignore` para prevenir que ele seja adicionado novamente no futuro.
- Criar um commit com as mudanças realizadas e abrir um Pull Request.

### Exemplo de Commit:
> _Remove `.DS_Store` da raiz do projeto e atualiza `.gitignore`_

**Comment by NewtonFernandis** [comment]
Você pode me atribuir esse problema?

**Comment by NewtonFernandis** [comment]
@lhsazevedo Eu levantei uma solicitação de pull, revise e me avise se precisar de alguma alteração
