### ISSUE TITLE
Remover seção em inglês no README

### ISSUE THREAD

**Issue by lhsazevedo** [comuREDE/core#15]
### Objetivo
Precisamos remover a seção em inglês do README para manter a organização e a consistência da documentação. No futuro, podemos criar uma versão separada do README em inglês, se necessário.

### Contexto
- **Motivo**: O README atualmente contém seções duplicadas em inglês e português. Como estamos em uma fase de melhorias na documentação, a remoção da parte em inglês é necessária para manter o arquivo mais organizado. Uma versão em inglês pode ser adicionada em um documento separado no futuro, conforme o projeto evolui.
- **Impacto**: Isso ajuda a manter a documentação limpa e organizada, facilitando a leitura e a manutenção.

### Tarefas
- Remover a seção em inglês intitulada "WHAT IS comuREDE?" e qualquer outro conteúdo em inglês presente no README.
- Garantir que o README permaneça claro e bem formatado após a remoção do trecho.
- Criar um commit com as mudanças realizadas e abrir um Pull Request.

### Exemplo de Commit:
> _Remove conteúdo em inglês do README para melhorar a organização_

**Comment by rnihesh** [comment]
@lhsazevedo assign me , and add hacktoberfest-accepted tag to this issue, pushing the merge request...

**Comment by rnihesh** [comment]
can you please add hacktoberfest-accepeted tag to this issue, so that I'll get my badge

**Comment by lhsazevedo** [comment]
Already added it in your PR #16

**Comment by rnihesh** [comment]
Okie Thanks :)
